### PR TITLE
Cubic function potential

### PR DESCRIPTION
**Pull request by yutakasi634**
Implementation and documents for UniformCubicFunctionPotential.
This potential is a global pair potential for representing a simple pan shape.
This pull request includes

- The class for UniformCubicFunctionPotential.
- The reading function for this potential.
- The documents for this potential.
- The tests for this potential.

### CODE REVIEW

**Review by ToruNiina — COMMENTED** [review]
Basically the implementation looks good. But the name looks too general, because it only represents a degree of the function, not the shape or the functionality. What about `UniformCubicPanPotential`?

**Comment by yutakasi634** [comment]
> Basically the implementation looks good. But the name looks too general, because it only represents a degree of the function, not the shape or the functionality. What about `UniformCubicPanPotential`?

OK. I renamed the potential and changed files following that.

**Review by ToruNiina — APPROVED** [review]
LGTM.

**Comment by ToruNiina** [comment]
After checking CI, I will merge it.

**Pull request merged**
